### ISSUE TITLE
Wallpapers, movie information not shown after csv import

### ISSUE THREAD

**Issue by Ollo1** [Alcidauk/CineLog#4] opened 2018-11-14 02:58 UTC
CineLog v1.0
Android 8.0

After export and re-import of csv data the wallpapers and movie information is not shown and will not refresh after re-start of the application. Instead a generic icon is shown.

**Comment by Alcidauk** [comment] 2018-11-15 11:59
Hi,

seems the import process is unable to put back data in db. Could you to attach the file you tried to import to this issue ?

**Comment by Ollo1** [comment] 2018-11-15 15:04
Thanks for the feedback. Attached you find the file. I renamed it to allow upload.
[import.txt](https://github.com/Alcidauk/CineLog/files/2585828/import.txt)

**Comment by Alcidauk** [comment] 2018-11-16 09:51
Ok, got it. Thanks for the file. 

The issue is due to date formatting, I need to fix it to avoid the issue. I'll do that quickly to prevent issues with import.

**Comment by Ollo1** [comment] 2018-11-20 19:33
Yes this sound reasonable. However the behaviour described seems not to work. Please try this
1. Have a number of films.
2. Export
3. Delete one film
4. Import previous export.
Deleted filmis back however all other as entries are remimported and leads to duplicates.

If I delete the database everthing including images is imported.

**Comment by Alcidauk** [comment] 2018-11-21 13:32
I was waiting for your opinion before avoiding duplicates, so I didn't include it in v1.0.1. 

I will do this as soon as possible. However, films without wallpaper and informations when reimporting data should be fixed, isn't it ?

**Comment by Ollo1** [comment] 2018-11-21 18:23
Sorry I misunderstood. But yes I agree on your proposal. I confirm the re-import worked without issue.
Thanks.

**Comment by Alcidauk** [comment] 2018-12-02 13:13
With the new release (v1.1), I improved the system. For now, all movies in the imported file ERASE movies that were in the db. In the next release, I'll add an option in the import view to avoid erasing movies if already existing.

**Closed by Alcidauk** 2018-12-02 13:13 UTC
